spring.application.name=Viviane.Ai

# Dialeto específico do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#CREDENCIAIS DO BANCO DE DADOS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA E HIBERNATE
# Valida o schema com base nas entidades. Usa Flyway para gerenciar o schema.
spring.jpa.hibernate.ddl-auto=validate

# Log de SQL no console (útil em dev)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#WEBCLIENT
openai.api.key=${OPENAI_API_KEY}
